name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "docker", "main" ]
  pull_request:
    branches: [ "docker", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build --no-cache --force-rm 
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Test the Docker image
        run: docker compose up -d 
  push_to_registry:
    runs-on: self-hosted
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Docker Hub
        uses: docker/login-action@3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}